spring:
  # Jackson 配置项
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    serialization:
#      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
#      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
#      fail-on-empty-beans: false # 允许序列化无属性的 Bean

forest:
  backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
  max-connections: 1000        # 连接池最大连接数（默认为 500）
  max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-async-thread-size: 300   # [自v1.5.21版本起可用] 最大异步线程数
  max-async-queue-size: 16     # [自v1.5.22版本起可用] 最大异步线程池队列大小
  connect-timeout: 60000        # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 60000           # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 0           # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）


third:
  appId: jwb8d349a5d8f1cef5
  appSecret: 38b4cb8537d7d84446a4ca0297beb9d84da2e6516346d87245f5d20513789af4
  # 注意 url必须以http或者https开头，否则使用的这个第三方库会自动在前面加一个localhost
#  url: 'http://localhost:48080/app-api/third/order/'
  url: 'https://s.v3.rd.jwcab.com/prod-api/app-api/third/order/'

server:
  port: 8081